### ISSUE TITLE
Question does the netcdf pas file still work on delphi community edition 10.4

### ISSUE THREAD

**Issue by Linuxuser1234** [virtorio13/DelphiNetCDF#1]

**Comment by virtorio13** [comment]
Yes, as long as it's NetCDF classic files you're working with.

**Comment by Linuxuser1234** [comment]
@virtorio13 i made a icon to display on a sphere would you know how to get data from  thredds (TDS catalog)  satellite->GLM and get the icon displayed on the sphere?

**Comment by virtorio13** [comment]
Sorry, I don't really work with NetCDF files myself nor have any knowledge of these datasets.
